export const GET_TICKERS = 'GET_TICKERS';
export const ADD_TICKER = 'ADD_TICKER';
export const DELETE_TICKER = 'DELETE_TICKER';
export const EDIT_QUANTITY = 'EDIT_QUANTITY';
export const UPDATE_INDEX = 'UPDATE_INDEX';

export const GET_ALL_PORTFOLIO = 'GET_ALL_PORTFOLIO';
export const CREATE_NEW_PORTFOLIO = 'CREATE_NEW_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';

export const GET_CURRENT_PRICE = 'GET_CURRENT_PRICE';
export const GET_COMPANY_STAT = 'GET_COMPANY_STAT';
export const GET_COMPANY_FINANCIAL = 'GET_COMPANY_FINANCIAL';
export const GET_COMPANY_FINANCIAL_ANNUAL = 'GET_COMPANY_FINANCIAL_ANNUAL';
export const GET_COMPANY_NEWS = 'GET_COMPANY_NEWS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERRORS = 'GET_ERRORS';
